class Error(Exception):
	pass

class ExitException(Exception):
	pass